// AUTO-GENERATED by scripts/gen-location-names.cjs — do not hand-edit.
// Re-run the script to regenerate after changing LOCATION_PICKUP_MAP or the logic JSON files.

/**
 * LOCATION_NAME_MAP
 *
 * Maps each region's tracker array index to the authoritative Randovania room (area) name.
 * Indexed as LOCATION_NAME_MAP[region][arrayIndex] === roomName.
 *
 * Room names are area keys from public/logic/<Region>.json (not item names — those are
 * randomized). Duplicate room names across markers are expected; position disambiguates.
 */
export const LOCATION_NAME_MAP = {
  artaria: [
    "Transport to Burenia", "Screw Attack Room", "Screw Attack Room", "Freezer",
    "Waterfall", "Teleport to Cataris", "Charge Beam Access", "Energy Recharge Station South",
    "EMMI Zone Exit Northwest", "EMMI Zone Spinner", "EMMI Zone Exit North", "EMMI Zone First Entrance",
    "Arbitrary Enky Room", "Melee Tutorial Room", "David Jaffe Room", "Melee Tutorial Room",
    "Invisible Corpius Room", "Proto EMMI Introduction", "Thermal Device", "East Lava Missile Room",
    "Hot Cataris Shortcut", "Teleport to Cataris", "Speed Hallway", "Varia Suit Tutorial North",
    "Speed Hallway", "Waterfall", "Charge Tutorial", "Shutter Platform Puzzle",
    "EMMI Zone Hub", "Charge Beam Room", "Central Unit Access", "Corpius Arena",
    "Screw Attack Room", "Grapple Beam Room", "Varia Suit Room",
  ],
  cataris: [
    "Teleport to Ghavoran", "Kraid Eyedoor Room", "Teleport to Ghavoran", "EMMI Zone Exits West",
    "Teleport to Dairon", "Z-57 Heat Room West (Right)", "Above Z-57 Fight", "EMMI Zone Hidden Missile Room",
    "Z-57 Heat Room East", "Dairon Transport Access", "Transport to Artaria", "Double Obsydomithon Room",
    "Lava Button East Access", "Teleport to Artaria (Blue)", "Teleport to Artaria (Red)", "Thermal Device Room North",
    "Underlava Puzzle Room 2", "Thermal Device Room North", "Teleport to Artaria (Blue)", "EMMI Zone Item Tunnel",
    "Diffusion Beam Room", "Diffusion Beam Room", "Central Unit Access", "Above Z-57 Fight",
    "Kraid Arena",
  ],
  dairon: [
    "Freezer", "Freezer", "Save Station West Tunnels", "Hidden Grapple Shortcut Room",
    "EMMI Zone Exit Northwest", "Bomb Room", "Cross Bomb Puzzle Room", "Early Grapple Room",
    "Big Hub", "Early Grapple Room", "Teleport to Artaria", "Storm Missile Gate Room",
    "Early Grapple Access", "Central Unit Access", "Yellow EMMI Introduction", "Energy Recharge Station West",
    "Shinespark Tutorial", "Transport to Artaria", "EMMI Zone Exit North", "Lake Puzzle Room",
    "Wide Beam Room", "Bomb Room", "Central Unit Access",
  ],
  burenia: [
    "Main Hub Tower Middle", "Main Hub Tower Top", "Energy Recharge South", "Gravity Suit Tower",
    "Underneath Drogyga", "Upper Burenia Hub", "Burenia Hub to Dairon", "Transport to Artaria",
    "Teleport to Ferenia", "Early Gravity Speedboost Room 1", "Gravity Suit Tower", "Main Hub Tower Middle",
    "Early Gravity Speedboost Room 1", "Burenia Hub to Dairon", "Main Hub Tower Top", "Storm Missile Gate Room",
    "Gravity Suit Room", "Flash Shift Room", "Gravity Suit Room", "Drogyga Arena",
  ],
  ferenia: [
    "Separate Tunnels Room", "Separate Tunnels Room", "Pitfall Puzzle Room", "Space Jump Room",
    "Cold Room (Storm Missile Gate)", "Escue Eyedoor Room", "Space Jump Room", "Fan Room",
    "Total Recharge Station", "Energy Recharge Station Secret", "Speedboost Slopes Maze", "Path to Escue",
    "Twin Robot Arena", "Purple EMMI Introduction", "Space Jump Room", "Escue Arena",
    "Purple EMMI Arena",
  ],
  ghavoran: [
    "Cross Bomb Tutorial", "Above Pulse Radar", "Golzuna Tower", "Teleport to Burenia",
    "Total Recharge Station North", "Map Station Access Secret", "Left Entrance", "Right Entrance",
    "Elun Transport Access", "Dairon Transport Access", "Super Missile Room Access", "Golzuna Tower",
    "Spin Boost Tower", "Spin Boost Tower", "Spin Boost Tower", "Central Unit Access",
    "Pulse Radar Room", "Super Missile Room", "Spin Boost Room", "Golzuna Arena",
  ],
  elun: [
    "Horizontal Bomb Maze", "Fan Room", "Ammo Recharge Station", "Vertical Bomb Maze",
    "Plasma Beam Room",
  ],
  hanubia: [
    "Ferenia Shortcut", "Total Recharge Station North", "Speedboost Puzzle Room", "Orange EMMI Introduction",
  ],
};

/**
 * locationNameFor(region, index)
 *
 * Return the room name for a tracker location.
 *
 * @param {string} region - lower-case region key, e.g. "artaria"
 * @param {number} index  - 0-based tracker array index
 * @returns {string} the Randovania room name, or a graceful fallback on out-of-range index
 * @throws {Error} if region is unknown
 */
export function locationNameFor(region, index) {
  const names = LOCATION_NAME_MAP[region];
  if (!names) {
    throw new Error(`locationNameFor: unknown region "${region}". Known: ${Object.keys(LOCATION_NAME_MAP).join(", ")}.`);
  }
  if (index < 0 || index >= names.length) {
    // Graceful fallback: return the capitalized region name rather than crashing the UI.
    return region.charAt(0).toUpperCase() + region.slice(1);
  }
  return names[index];
}
