export default {
  state: {
    locations: [
      {
        area: "1",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:386px",
        left: "left:28px",
      },
      {
        area: "2",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:386px",
        left: "left:139px",
      },
      {
        area: "3",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:430px",
        left: "left:132px",
      },
      {
        area: "4",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:410px",
        left: "left:187px",
      },
      {
        area: "5",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:360px",
        left: "left:242px",
      },
      {
        area: "6",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:287px",
        left: "left:298px",
      },
      {
        area: "7",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:494px",
        left: "left:378px",
      },
      {
        area: "8",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:460px",
        left: "left:407px",
      },
      {
        area: "9",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:337px",
        left: "left:395px",
      },
      {
        area: "10",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:392px",
        left: "left:511px",
      },
      {
        area: "11",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:303px",
        left: "left:518px",
      },
      {
        area: "12",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:364px",
        left: "left:604px",
      },
      {
        area: "13",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:299px",
        left: "left:648px",
      },
      {
        area: "14",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:409px",
        left: "left:682px",
      },
      {
        area: "15",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:312px",
        left: "left:726px",
      },
      {
        area: "16",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:385px",
        left: "left:728px",
      },
      {
        area: "17",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:321px",
        left: "left:748px",
      },
      {
        area: "18",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:380px",
        left: "left:769px",
      },
      {
        area: "19",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:331px",
        left: "left:810px",
      },
      {
        area: "20",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:312px",
        left: "left:828px",
      },
      {
        area: "21",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:295px",
        left: "left:966px",
      },
      {
        area: "22",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:349px",
        left: "left:319px",
      },
      {
        area: "1m",
        checked: false,
        type: "missiles",
        amount: 10,
        top: "top:463px",
        left: "left:324px",
      },
      {
        area: "2m",
        checked: false,
        type: "missiles",
        amount: 10,
        top: "top:235px",
        left: "left:365px",
      },
      {
        area: "1ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:466px",
        left: "left:266px",
      },
      {
        area: "2ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:335px",
        left: "left:230px",
      },
      {
        area: "1ef",
        checked: false,
        type: "energyFull",
        amount: 1,
        top: "top:507px",
        left: "left:624px",
      },
      {
        area: "2ef",
        checked: false,
        type: "energyFull",
        amount: 1,
        top: "top:209px",
        left: "left:215px",
      },
      {
        area: "1pb",
        checked: false,
        type: "powerBomb",
        amount: 1,
        top: "top:333px",
        left: "left:436px",
      },
    ],
  },
  mutations: {
    UPDATE_AREA(state, location, index) {
      !this.locations[index].checked;
    },
  },
  actions: {
    updateArea({ commit }, location, index) {
      console.log(location, index);
      commit("UPDATE_AREA", location, index);
    },
  },
  namespaced: true,
};
