export default {
  state: {
    locations: [
      {
        area: "1",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:213px",
        left: "left:304px",
      },
      {
        area: "2",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:262px",
        left: "left:312px",
      },
      {
        area: "3",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:300px",
        left: "left:269px",
      },
      {
        area: "4",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:310px",
        left: "left:295px",
      },
      {
        area: "5",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:295px",
        left: "left:371px",
      },
      {
        area: "6",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:193px",
        left: "left:463px",
      },
      {
        area: "7",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:230px",
        left: "left:475px",
      },
      {
        area: "8",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:312px",
        left: "left:691px",
      },
      {
        area: "9",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:231px",
        left: "left:728px",
      },
      {
        area: "10",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:332px",
        left: "left:736px",
      },
      {
        area: "11",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:172px",
        left: "left:839px",
      },
      {
        area: "1m",
        checked: false,
        type: "missiles",
        amount: 10,
        top: "top:350px",
        left: "left:379px",
      },
      {
        area: "1ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:316px",
        left: "left:620px",
      },
      {
        area: "2ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:394px",
        left: "left:303px",
      },
      {
        area: "3ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:214px",
        left: "left:572px",
      },
      {
        area: "4ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:184px",
        left: "left:286px",
      },
      {
        area: "1ef",
        checked: false,
        type: "energyFull",
        amount: 1,
        top: "top:262px",
        left: "left:464px",
      },
      {
        area: "1pb",
        checked: false,
        type: "powerBomb",
        amount: 1,
        top: "top:309px",
        left: "left:755px",
      },
      {
        area: "2pb",
        checked: false,
        type: "powerBomb",
        amount: 1,
        top: "top:210px",
        left: "left:521px",
      },
      {
        area: "3pb",
        checked: false,
        type: "powerBomb",
        amount: 1,
        top: "top:350px",
        left: "left:460px",
      },
    ],
  },
  mutations: {
    UPDATE_AREA(state, location, index) {
      !this.locations[index].checked;
    },
  },
  actions: {
    updateArea({ commit }, location, index) {
      console.log(location, index);
      commit("UPDATE_AREA", location, index);
    },
  },
  namespaced: true,
};
