export default {
  state: {
    locations: [
      {
        area: "1",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:209px",
        left: "left:737px",
      },
      {
        area: "2",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:169px",
        left: "left:521px",
      },
      {
        area: "3",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:229px",
        left: "left:551px",
      },
      {
        area: "4",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:274px",
        left: "left:589px",
      },
      {
        area: "5",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:293px",
        left: "left:599px",
      },
      {
        area: "6",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:356px",
        left: "left:374px",
      },
      {
        area: "7",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:461px",
        left: "left:115px",
      },
      {
        area: "8",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:490px",
        left: "left:211px",
      },
      {
        area: "9",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:400px",
        left: "left:395px",
      },
      {
        area: "10",
        checked: false,
        type: "missiles",
        amount: 2,
        top: "top:479px",
        left: "left:439px",
      },
      {
        area: "1m",
        checked: false,
        type: "missiles",
        amount: 10,
        top: "top:442px",
        left: "left:345px",
      },
      {
        area: "1ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:152px",
        left: "left:560px",
      },
      {
        area: "2ep",
        checked: false,
        type: "energyPart",
        amount: 1,
        top: "top:313px",
        left: "left:403px",
      },
      {
        area: "1ef",
        checked: false,
        type: "energyFull",
        amount: 1,
        top: "top:218px",
        left: "left:453px",
      },
      {
        area: "1pb",
        checked: false,
        type: "powerBomb",
        amount: 1,
        top: "top:152px",
        left: "left:432px",
      },
    ],
  },
  mutations: {
    UPDATE_AREA(state, location, index) {
      !this.locations[index].checked;
    },
  },
  actions: {
    updateArea({ commit }, location, index) {
      console.log(location, index);
      commit("UPDATE_AREA", location, index);
    },
  },
  namespaced: true,
};
